-- AlterTable
ALTER TABLE "Scores" ALTER COLUMN "holder_score" SET DEFAULT 0,
ALTER COLUMN "holder_score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "volume_score" SET DEFAULT 0,
ALTER COLUMN "volume_score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "age_score" SET DEFAULT 0,
ALTER COLUMN "age_score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "community_user_experience_score" SET DEFAULT 0,
ALTER COLUMN "community_user_experience_score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "community_innovation_score" SET DEFAULT 0,
ALTER COLUMN "community_innovation_score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "community_engagement_score" SET DEFAULT 0,
ALTER COLUMN "community_engagement_score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "community_art_work_score" SET DEFAULT 0,
ALTER COLUMN "community_art_work_score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "audit_score" SET DEFAULT 0,
ALTER COLUMN "audit_score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "community_reliability_score" SET DEFAULT 0,
ALTER COLUMN "community_reliability_score" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "community_support_score" SET DEFAULT 0,
ALTER COLUMN "community_support_score" SET DATA TYPE DOUBLE PRECISION;
