version: "3.9"

services:
  database:
    image: postgres
    container_name: voyager_database_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=voyager
    volumes:
      - pgdata:/data/postgres
  redis:
    image: redis
    container_name: voyager_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data/redis

volumes:
  pgdata:
    driver: local
  redis:
    driver: local